# Generated by Django 4.1.4 on 2023-01-17 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='user',
        ),
    ]
