# Generated by Django 4.1.4 on 2023-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accountmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='telno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
