# Generated by Django 4.1.4 on 2023-01-20 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_accountmodel_telno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='popular',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='telno',
        ),
        migrations.CreateModel(
            name='twitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twit', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('twitImg', models.FileField(upload_to='twits/')),
                ('createdBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='mySharings',
            field=models.ManyToManyField(to='api.twitsmodel'),
        ),
    ]
