# Generated by Django 4.1.4 on 2023-01-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_accountmodel_mysharings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='mySharings',
            field=models.ManyToManyField(blank=True, null=True, to='api.accountmodel'),
        ),
    ]
