# Generated by Django 4.1.4 on 2023-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_accountmodel_mysharings'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='mySharings',
            field=models.ManyToManyField(to='api.twitsmodel'),
        ),
    ]
