# Generated by Django 4.1.4 on 2023-01-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_accountmodel_mysharings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitsmodel',
            name='twit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='twitsmodel',
            name='twitImg',
            field=models.FileField(null=True, upload_to='twits/'),
        ),
    ]
