# Generated by Django 4.1.4 on 2023-01-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_twitsmodel_twit_alter_twitsmodel_twitimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='mySharings',
        ),
    ]
