# Generated by Django 4.1.4 on 2023-01-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_accountmodel_mysharings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='profileImg',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
