# Generated by Django 4.1.4 on 2023-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_accountmodel_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
