# Generated by Django 4.1.4 on 2023-01-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_accountmodel_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='profileImg',
            field=models.TextField(null=True),
        ),
    ]
