# Generated by Django 4.1.4 on 2023-01-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_accountmodel_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitsmodel',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accountmodel'),
        ),
    ]
