# Generated by Django 4.1.4 on 2023-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_twitsmodel_createdby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitsmodel',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='twitsmodel',
            name='twitImg',
            field=models.TextField(null=True),
        ),
    ]
