# Generated by Django 4.1.4 on 2023-01-24 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_twitsmodel_date_alter_twitsmodel_twitimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.CharField(max_length=100)),
                ('sharing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.twitsmodel')),
            ],
        ),
    ]
