# Generated by Django 4.1.4 on 2023-01-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('followed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.accountmodel')),
            ],
        ),
    ]
