# Generated by Django 4.1.4 on 2023-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_followings'),
    ]

    operations = [
        migrations.AddField(
            model_name='followings',
            name='followerId',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='likes',
            name='likeId',
            field=models.IntegerField(null=True),
        ),
    ]
